with open('lib/survey-data.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Find the learning scoring block: from "  // 思维模式" line to the end of
# selfRegulationAvg block. Replace with the new formulas.
# Use unique substring anchors.
anchor_start = '  // 思维模式 (Q1,Q3,Q4,Q5,Q6 正向；Q2 反向)'
anchor_end = '  const average10: Record<Dimension, number> = {'

assert anchor_start in content, f"anchor_start not found in content length {len(content)}"
assert anchor_end in content, "anchor_end not found"

s = content.index(anchor_start)
e = content.index(anchor_end, s)

new_learning_block = (
    '  // 思维模式 (a[1], a[2] 反向；a[3], a[4] 正向)\n'
    '  const thinkingAvg = avg([\n'
    '    score10(learningAnswers, 1, true),\n'
    '    score10(learningAnswers, 2, true),\n'
    '    score10(learningAnswers, 3),\n'
    '    score10(learningAnswers, 4),\n'
    '  ]);\n'
    '\n'
    '  // 自主性 (a[5] 正向；a[6] 反向；a[7] 正向；a[8] 反向)\n'
    '  const autonomyAvg = avg([\n'
    '    score10(learningAnswers, 5),\n'
    '    score10(learningAnswers, 6, true),\n'
    '    score10(learningAnswers, 7),\n'
    '    score10(learningAnswers, 8, true),\n'
    '  ]);\n'
    '\n'
    '  // 胜任感 (a[9] 反向；a[10], a[11], a[12] 正向；a[13], a[14] 反向)\n'
    '  const competenceAvg = avg([\n'
    '    score10(learningAnswers, 9, true),\n'
    '    score10(learningAnswers, 10),\n'
    '    score10(learningAnswers, 11),\n'
    '    score10(learningAnswers, 12),\n'
    '    score10(learningAnswers, 13, true),\n'
    '    score10(learningAnswers, 14, true),\n'
    '  ]);\n'
    '\n'
    '  // 归属感 (a[15], a[16] 正向；a[17] 反向；a[18], a[19] 正向；a[20], a[21] 反向；a[22] 正向)\n'
    '  const belongingAvg = avg([\n'
    '    score10(learningAnswers, 15),\n'
    '    score10(learningAnswers, 16),\n'
    '    score10(learningAnswers, 17, true),\n'
    '    score10(learningAnswers, 18),\n'
    '    score10(learningAnswers, 19),\n'
    '    score10(learningAnswers, 20, true),\n'
    '    score10(learningAnswers, 21, true),\n'
    '    score10(learningAnswers, 22),\n'
    '  ]);\n'
    '\n'
    '  // 深层动机 (a[23], a[27], a[31], a[35], a[39])\n'
    '  const deepMotivationAvg = avg([\n'
    '    score10(learningAnswers, 23),\n'
    '    score10(learningAnswers, 27),\n'
    '    score10(learningAnswers, 31),\n'
    '    score10(learningAnswers, 35),\n'
    '    score10(learningAnswers, 39),\n'
    '  ]);\n'
    '\n'
    '  // 表层动机 (a[24], a[28], a[32], a[36], a[40])\n'
    '  const surfaceMotivationAvg = avg([\n'
    '    score10(learningAnswers, 24),\n'
    '    score10(learningAnswers, 28),\n'
    '    score10(learningAnswers, 32),\n'
    '    score10(learningAnswers, 36),\n'
    '    score10(learningAnswers, 40),\n'
    '  ]);\n'
    '\n'
    '  // 深层方法 (a[25], a[29], a[33], a[37], a[41] — 全部反向)\n'
    '  const deepMethodAvg = avg([\n'
    '    score10(learningAnswers, 25, true),\n'
    '    score10(learningAnswers, 29, true),\n'
    '    score10(learningAnswers, 33, true),\n'
    '    score10(learningAnswers, 37, true),\n'
    '    score10(learningAnswers, 41, true),\n'
    '  ]);\n'
    '\n'
    '  // 表层方法 (a[26], a[30], a[34], a[38], a[42])\n'
    '  const surfaceMethodAvg = avg([\n'
    '    score10(learningAnswers, 26),\n'
    '    score10(learningAnswers, 30),\n'
    '    score10(learningAnswers, 34),\n'
    '    score10(learningAnswers, 38),\n'
    '    score10(learningAnswers, 42),\n'
    '  ]);\n'
    '\n'
    '  // 自我效能感 (a[43]..a[51]，共 9 题)\n'
    '  const selfEfficacyAvg = avg([\n'
    '    score10(learningAnswers, 43),\n'
    '    score10(learningAnswers, 44),\n'
    '    score10(learningAnswers, 45),\n'
    '    score10(learningAnswers, 46),\n'
    '    score10(learningAnswers, 47),\n'
    '    score10(learningAnswers, 48),\n'
    '    score10(learningAnswers, 49),\n'
    '    score10(learningAnswers, 50),\n'
    '    score10(learningAnswers, 51),\n'
    '  ]);\n'
    '\n'
    '  // 学习自我调节 (a[52] 正向；a[53] 反向；a[54], a[55], a[56] 正向；a[57], a[58] 反向；a[59], a[60] 正向)\n'
    '  const selfRegulationAvg = avg([\n'
    '    score10(learningAnswers, 52),\n'
    '    score10(learningAnswers, 53, true),\n'
    '    score10(learningAnswers, 54),\n'
    '    score10(learningAnswers, 55),\n'
    '    score10(learningAnswers, 56),\n'
    '    score10(learningAnswers, 57, true),\n'
    '    score10(learningAnswers, 58, true),\n'
    '    score10(learningAnswers, 59),\n'
    '    score10(learningAnswers, 60),\n'
    '  ]);\n'
    '\n'
)

content = content[:s] + new_learning_block + content[e:]

# Write file
with open('lib/survey-data.ts', 'w', encoding='utf-8') as f:
    f.write(content)
print("scoring block replaced")
